CREATE TABLE NYCCAB.TRIP_ADV AS
   (SELECT DRIVER,
   			PICKUP_TIME
   			PICKUP_LAT,
   			PICKUP_LONG,
   			YEAR(PICKUP_TIME) AS YEAR,
   			MONTH(PICKUP_TIME) AS MONTH,
   			ROUND(DAYOFMONTH(PICKUP_TIME) / 7, 0, ROUND_UP) AS WEEKOFMONTH,
   			WEEKDAY(PICKUP_TIME) AS WEEKDAY,
   			HOUR(PICKUP_TIME) AS HOUR
   FROM FARE
   WHERE
   		YEAR(PICKUP_TIME) != 2015 AND
   		PICKUP_LAT >= 35 AND PICKUP_LAT <= 45 AND
   		PICKUP_LONG >= -78 AND PICKUP_LONG <= -68)
