CREATE COLUMN TABLE NYCCAB.FARE_ADV AS
   (SELECT DRIVER,
   			PICKUP_TIME,
   			TOTAL,
   			YEAR(PICKUP_TIME) AS YEAR,
   			MONTH(PICKUP_TIME) AS MONTH,
   			ROUND(DAYOFMONTH(PICKUP_TIME) / 7, 0, ROUND_UP) AS WEEKOFMONTH
   FROM FARE
   WHERE FARE < 1001 AND
   		TOTAL > 0 AND
   		YEAR(PICKUP_TIME) != 2015 AND
   		DRIVER >= 1000000000)

CREATE TABLE NYCCAB.FARE_ADV (
DRIVER int,
PICKUP_TIME timestamp,
TOTAL int,
YEAR int,
MONTH int,
WEEK_OF_MONTH int)

CREATE COLUMN TABLE NYCCAB.FARE_ADV_COL AS (SELECT DRIVER, PICKUP_TIME, TOTAL, YEAR(PICKUP_TIME) AS YEAR, MONTH(PICKUP_TIME) AS MONTH, ROUND(DAYOFMONTH(PICKUP_TIME) / 7, 0, ROUND_UP) AS WEEKOFMONTH FROM NYCCAB.FARE WHERE FARE < 1001 AND TOTAL > 0 AND YEAR(PICKUP_TIME) != 2015 AND DRIVER >= 1000000000)

