SELECT
	ROUND(CAST(PICKUP_LAT as DOUBLE),3), ROUND(CAST(PICKUP_LONG as DOUBLE),3), COUNT(*)
FROM
	NYCCAB.TRIP
WHERE
	? AND
	MONTH(TO_DATE(PICKUP_TIME)) in ? AND
	ROUND(DAYOFMONTH(TO_DATE(PICKUP_TIME)) / 7, 0, ROUND_UP) in ? AND
	PICKUP_LAT <= ? AND PICKUP_LAT >= ? AND
	PICKUP_LONG <= ? AND PICKUP_LONG >= ? AND
	HOUR(PICKUP_TIME) <= ? AND HOUR(PICKUP_TIME) >= ? AND
	WEEKDAY(TO_DATE(PICKUP_TIME)) <= ? AND WEEKDAY(TO_DATE(PICKUP_TIME)) >= ?
GROUP BY
	ROUND(CAST(PICKUP_LAT as DOUBLE),3), ROUND(CAST(PICKUP_LONG as DOUBLE),3)
