SELECT
  HOUR(PICKUP_TIME), WEEKDAY(TO_DATE(PICKUP_TIME))
FROM
  NYCCAB.TRIP
WHERE
  /*((PICKUP_TIME BETWEEN TO_DATE('2011-01-01', 'YYYY-MM-DD') AND TO_DATE('2011-12-31', 'YYYY-MM-DD')) OR
  (PICKUP_TIME BETWEEN TO_DATE('2013-01-01', 'YYYY-MM-DD') AND TO_DATE('2013-12-31', 'YYYY-MM-DD'))) AND*/
  ? AND
  MONTH(TO_DATE(PICKUP_TIME)) in ? AND
  ROUND(DAYOFMONTH(TO_DATE(PICKUP_TIME)) / 7, 0, ROUND_UP) in ? AND
  PICKUP_LAT <= ? AND PICKUP_LAT >= ? AND
  PICKUP_LONG <= ? AND PICKUP_LONG >= ?

/*
SELECT
  HOUR(PICKUP_TIME), WEEKDAY(PICKUP_TIME)
FROM
  NYCCAB.TRIP
WHERE
  YEAR(PICKUP_TIME) in ? AND
  MONTH(PICKUP_TIME) in ? AND
  ROUND(DAYOFMONTH(PICKUP_TIME) / 7, 0, ROUND_UP) in ? AND
  PICKUP_LAT <= ? AND PICKUP_LAT >= ? AND
  PICKUP_LONG <= ? AND PICKUP_LONG >= ?
*/
