SELECT
  HOUR(PICKUP_TIME), WEEKDAY(TO_DATE(PICKUP_TIME)), COUNT(*)
FROM
  NYCCAB.TRIP
WHERE
  ? AND
  MONTH(TO_DATE(PICKUP_TIME)) in ? AND
  ROUND(DAYOFMONTH(TO_DATE(PICKUP_TIME)) / 7, 0, ROUND_UP) in ? AND
  PICKUP_LAT <= ? AND PICKUP_LAT >= ? AND
  PICKUP_LONG <= ? AND PICKUP_LONG >= ?
GROUP BY HOUR(PICKUP_TIME), WEEKDAY(TO_DATE(PICKUP_TIME))
