SELECT
  week, AVG(TOTAL)
FROM
  (
    SELECT
      ROUND(DAYOFMONTH(PICKUP_TIME) / 7, 0, ROUND_UP) as week, TOTAL
    FROM
      NYCCAB.FARE
    WHERE
			YEAR(PICKUP_TIME) in ? AND MONTH(PICKUP_TIME) in ?
  )
GROUP BY
  week
ORDER BY
  week
