SELECT
  ROUND(DAYOFMONTH(TO_DATE(PICKUP_TIME)) / 7, 0, ROUND_UP), AVG(TOTAL)
FROM
  NYCCAB.FARE
WHERE
  ? AND
  MONTH(TO_DATE(PICKUP_TIME)) in (2,5)
GROUP BY
  ROUND(DAYOFMONTH(TO_DATE(PICKUP_TIME)) / 7, 0, ROUND_UP)
ORDER BY
  ROUND(DAYOFMONTH(TO_DATE(PICKUP_TIME)) / 7, 0, ROUND_UP)
